spring:
  rabbitmq:
    addresses: "localhost"

    listener:
      simple:
        default-requeue-rejected: false

#spring:
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username:
#    password:
#
#h2:
#  console:
#    enabled: true
#
#jpa:
#  hibernate:
#    ddl-auto: update
#    show-sql: true